//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "books")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub book_name: Option<String>,
    pub book_image: Option<String>,
    pub book_title: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub book_price: Option<f32>,
    pub category_id_id: i32,
    pub author_id_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::author_ids::Entity",
        from = "Column::AuthorIdId",
        to = "super::author_ids::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    AuthorIds,
    #[sea_orm(
        belongs_to = "super::category_ids::Entity",
        from = "Column::CategoryIdId",
        to = "super::category_ids::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    CategoryIds,
}

impl Related<super::author_ids::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthorIds.def()
    }
}

impl Related<super::category_ids::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CategoryIds.def()
    }
}
